Repository boostcampwm-2021/web20-PingPingsFriends, pull requests merged in 2021-11, with the labels that each got.

#8 [W2][D2][다람이&징징이] 프론트엔드 세팅
  front/.env
  front/.gitignore
  front/.prettierrc
  front/Dockerfile
  front/README.md
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/public/logo192.png
  front/public/logo512.png
  front/public/manifest.json
  front/public/robots.txt
  front/src/App.css
  front/src/App.test.tsx
  front/src/App.tsx
  front/src/components/dummy.tsx
  front/src/index.css
  front/src/index.tsx
  front/src/logo.svg
  front/src/pages/dummy.tsx
  front/src/react-app-env.d.ts
  front/src/reportWebVitals.ts
  front/src/setupTests.ts
  front/tsconfig.json
  front/yarn.lock
Labels: frontend, setting

#9 [W2][D2][스폰지밥&뚱이] 백엔드 세팅
  back/.eslintrc.js
  back/.gitignore
  back/.prettierrc
  back/README.md
  back/nest-cli.json
  back/package-lock.json
  back/package.json
  back/src/app.controller.spec.ts
  back/src/app.controller.ts
  back/src/app.module.ts
  back/src/app.service.ts
  back/src/database/database.module.ts
  back/src/database/database.providers.ts
  back/src/main.ts
  back/src/users/dto/create-user.dto.ts
  back/src/users/dto/update-user.dto.ts
  back/src/users/dto/userResponseDto.ts
  back/src/users/entities/user.entity.ts
  back/src/users/users.controller.spec.ts
  back/src/users/users.controller.ts
  back/src/users/users.module.ts
  back/src/users/users.providers.ts
  back/src/users/users.service.spec.ts
  back/src/users/users.service.ts
  back/test/app.e2e-spec.ts
  back/test/jest-e2e.json
  back/tsconfig.build.json
  back/tsconfig.json
Labels: backend, setting

#11 [W2][D3][다람이] 백엔드 docekrfile 작성
  back/.dockerignore
  back/Dockerfile
Labels: backend, setting

#14 [W2][D3][다람이&징징이] CRA 설정 및 라우팅
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/public/logo192.png
  front/public/logo512.png
  front/public/manifest.json
  front/public/robots.txt
  front/src/App.css
  front/src/App.tsx
  front/src/index.css
  front/src/index.tsx
  front/src/logo.svg
  front/src/pages/ExplorePage.tsx
  front/src/pages/MainPage.tsx
  front/src/pages/RegisterPage.tsx
  front/src/pages/UserPage.tsx
  front/src/reportWebVitals.ts
  front/src/reset.css
  front/src/setupTests.ts
  front/yarn.lock
Labels: frontend

#22 [W2][D3][뚱이] Object Storage 세팅
  back/.gitignore
  back/Dockerfile
  back/package-lock.json
  back/package.json
  back/src/app.module.ts
  back/src/database/database.config.ts
  back/src/main.ts
  back/src/s3/dto/create-s3.dto.ts
  back/src/s3/dto/s3ResponseDto.ts
  back/src/s3/dto/update-s3.dto.ts
  back/src/s3/entities/s3.entity.ts
  back/src/s3/s3.controller.spec.ts
  back/src/s3/s3.controller.ts
  back/src/s3/s3.module.ts
  back/src/s3/s3.service.spec.ts
  back/src/s3/s3.service.ts
  back/yarn.lock
Labels: backend, devops

#24 [W2][D3][징징이] 아바타, 헤더, 서식지 프리뷰 컴포넌트 추가
  front/src/App.test.tsx
  front/src/assets/icons/bottom_arrow.svg
  front/src/components/Habitat/HabitatPreview.tsx
  front/src/components/Habitat/index.test.tsx
  front/src/components/Header/Header.tsx
  front/src/components/Header/Place.tsx
  front/src/components/Header/UserInfo.tsx
  front/src/components/Header/index.test.tsx
  front/src/components/_common/Avatar/Avatar.tsx
  front/src/components/_common/Avatar/index.test.tsx
  front/src/lib/styles/Palette.ts
  front/src/lib/styles/mixin.ts
  front/src/reset.css
  front/src/setupTests.ts
Labels: frontend

#21 [W2][D3][다람이] 피드, FAB 컴포넌트 만들기
  front/package.json
  front/public/cat.jpg
  front/public/dog.jpeg
  front/public/dummy_feed.json
  front/src/assets/icons/add_circle.svg
  front/src/assets/icons/comment_btn.svg
  front/src/assets/icons/empty_heart_btn.svg
  front/src/assets/icons/more_vert_btn.svg
  front/src/assets/icons/zoom_out.svg
  front/src/components/Feed.tsx
  front/src/components/FeedFAB.tsx
  front/src/components/FeedScrollBox.tsx
  front/src/pages/FeedTestPage.tsx
  front/yarn.lock
Labels: frontend

#29 [W2][D4][징징이&다람이] 메인 페이지 합치기
  front/package.json
  front/public/cat.jpg
  front/public/default_avatar.png
  front/public/dog.jpeg
  front/public/dummy_feed.json
  front/public/favicon.ico
  front/public/index.html
  front/public/logo192.png
  front/public/logo512.png
  front/public/manifest.json
  front/public/robots.txt
  front/src/App.css
  front/src/App.test.tsx
  front/src/App.tsx
  front/src/assets/icons/add_circle.svg
  front/src/assets/icons/bottom_arrow.svg
  front/src/assets/icons/comment_btn.svg
  front/src/assets/icons/empty_heart_btn.svg
  front/src/assets/icons/hamburger_menu.svg
  front/src/assets/icons/more_vert_btn.svg
  front/src/assets/icons/zoom_out.svg
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedFAB.tsx
  front/src/components/Feed/FeedScrollBox.tsx
  front/src/components/Habitat/HabitatPreview.tsx
  front/src/components/Habitat/index.test.tsx
  front/src/components/Header/Header.tsx
  front/src/components/Header/Place.tsx
  front/src/components/Header/UserInfo.tsx
  front/src/components/Header/index.test.tsx
  front/src/components/_common/Avatar/Avatar.tsx
  front/src/components/_common/Avatar/index.test.tsx
  front/src/components/dummy.tsx
  front/src/index.css
  front/src/index.tsx
  front/src/lib/styles/Palette.ts
  front/src/lib/styles/mixin.ts
  front/src/logo.svg
  front/src/pages/ExplorePage.tsx
  front/src/pages/MainPage.tsx
  front/src/pages/RegisterPage.tsx
  front/src/pages/UserPage.tsx
  front/src/pages/dummy.tsx
  front/src/reportWebVitals.ts
  front/src/reset.css
  front/yarn.lock
Labels: frontend

#30 feat : [#26] 업로드된 이미지 url DB에 저장하기
  back/src/s3/s3.module.ts
  back/src/s3/s3.service.ts
  back/src/users/entities/user.entity.ts
  back/src/users/users.service.ts
Labels: backend, setting

#32 [W2][D4][다람이&뚱이] nginx conf 설정
  front/Dockerfile
  front/conf/conf.d/default.conf
Labels: frontend, setting

#33 [W2][D4][다람이] 프론트 실행 모드에 따른 환경변수 설정
  front/.dockerignore
  front/.env
  front/src/lib/constants/config.ts
  front/src/pages/TestPage.tsx
Labels: frontend, setting

#86 [W3][D1][징징이] 모달 구현
  front/public/index.html
  front/src/components/Modal/Modal.tsx
  front/src/components/Modal/useModal.tsx
Labels: frontend

#85 [W3][D1][다람이] 글쓰기 버튼 위치 반응형 & 피드 드롭박스
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedFAB.tsx
  front/src/components/_common/DropBox/DropBox.tsx
  front/src/global.css
  front/src/index.tsx
Labels: frontend

#93 [W3][D2][뚱이] Post API
  back/src/post/dto/create-post.dto.ts
  back/src/post/entities/post.entity.ts
  back/src/post/post.controller.ts
  back/src/post/post.module.ts
  back/src/post/post.service.ts
  back/src/s3/s3.service.ts
Labels: backend

#91 [W3][D2][징징이] 피드 캐러셀 구현, 좋아요 비/활성화 구현, 삭제 모달 구현
  front/public/dummy_feed.json
  front/public/제리.mp4
  front/public/제리2.mp4
  front/src/assets/icons/fill_heart_btn.svg
  front/src/assets/icons/left_arrow.svg
  front/src/assets/icons/right_arrow.svg
  front/src/components/Carousel/Arrow.tsx
  front/src/components/Carousel/Carousel.tsx
  front/src/components/Carousel/CarouselContents.tsx
  front/src/components/Carousel/Dots.tsx
  front/src/components/Carousel/Slide.tsx
  front/src/components/Carousel/useCarousel.ts
  front/src/components/Carousel/useClientRect.tsx
  front/src/components/DeleteModal/DeleteModal.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/HeartButton/HeartButton.tsx
  front/src/components/HeartButton/useLike.ts
  front/src/components/Modal/Modal.tsx
  front/src/components/Modal/useModal.tsx
  front/src/components/_common/DropBox/DropBox.tsx
  front/src/components/_common/DropBox/useDropBox.tsx
  front/src/global.css
  front/src/lib/styles/Palette.ts
Labels: frontend

#89 [W3][D2][다람이] 글쓰기 모달 구현
  front/src/assets/icons/add_contents.svg
  front/src/assets/icons/cancel_btn.svg
  front/src/assets/icons/cancel_btn3.svg
  front/src/assets/icons/check_circle.svg
  front/src/assets/icons/pet_btn.svg
  front/src/components/Feed/FeedFAB.tsx
  front/src/components/Write/Preview.tsx
  front/src/components/Write/WriteModal.tsx
  front/src/components/_common/SwipeBox/SwipeBox.tsx
  front/tsconfig.json
Labels: frontend

#99 [W3][D3][뚱이] 피드 API
  back/src/app.module.ts
  back/src/contents/dto/create-content.dto.ts
  back/src/hearts/dto/create-heart.dto.ts
  back/src/hearts/dto/update-heart.dto.ts
  back/src/hearts/entities/heart.entity.ts
  back/src/hearts/hearts.controller.spec.ts
  back/src/hearts/hearts.controller.ts
  back/src/hearts/hearts.module.ts
  back/src/hearts/hearts.service.spec.ts
  back/src/hearts/hearts.service.ts
  back/src/post/entities/post.entity.ts
  back/src/post/post.controller.ts
  back/src/post/post.module.ts
  back/src/post/post.service.ts
  back/src/s3/s3.service.ts
  back/src/users/entities/user.entity.ts
Labels: backend, setting

#96 [W3][D3][다람이] 사이드 서식지 컴포넌트 구현
  front/public/habitat/0.json
  front/public/habitat/1.json
  front/public/habitat/2.json
  front/src/assets/font/NanumPenScript-Regular.ttf
  front/src/assets/font/OFL.txt
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedScrollBox.tsx
  front/src/components/Habitat/HabitatPreview.tsx
  front/src/components/Header/UserInfo.tsx
  front/src/components/Modal/useModal.tsx
  front/src/components/Write/WriteModal.tsx
  front/src/components/_common/Avatar/Avatar.tsx
  front/src/hooks/useHabitatInfo.ts
  front/src/hooks/useHistory.ts
  front/src/lib/styles/magic.ts
  front/src/lib/utils/time.ts
  front/src/pages/MainPage.tsx
  front/src/reset.css
Labels: frontend

#100 [W3][D4][징징이] 서식지 변경 모달 띄우기
  front/src/components/Feed/FeedScrollBox.tsx
  front/src/components/HabitatModal/HabitatModal.tsx
  front/src/components/HabitatModal/HabitatsContainer.tsx
  front/src/components/Header/Header.tsx
  front/src/components/Header/Place.tsx
  front/src/hooks/useHabitatInfo.ts
  front/src/pages/MainPage.tsx
Labels: frontend

#102 [W3][D4][다람이] 글 상세보기 캐러셀 및 swipebox 구현
  front/src/components/DetailModal/DetailModal.tsx
  front/src/components/DetailModal/PreviewBox.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedScrollBox.tsx
  front/src/components/_common/Carousel/Carousel.tsx
  front/src/components/_common/Carousel/Dots.tsx
  front/src/components/_common/Carousel/Slide.tsx
  front/src/components/_common/Carousel/useMoveSlide.ts
Labels: frontend

#94 [W3][D2][스폰지밥] Comment API , Liked API, Habitat API
  back/.prettierrc
  back/package-lock.json
  back/package.json
  back/src/app.module.ts
  back/src/comment/comment.controller.spec.ts
  back/src/comment/comment.controller.ts
  back/src/comment/comment.module.ts
  back/src/comment/comment.service.ts
  back/src/comment/dto/create-comment.dto.ts
  back/src/comments/comment.repository.ts
  back/src/comments/comments.controller.spec.ts
  back/src/comments/comments.controller.ts
  back/src/comments/comments.module.ts
  back/src/comments/comments.service.spec.ts
  back/src/comments/comments.service.ts
  back/src/comments/dto/create-comment.dto.ts
  back/src/comments/dto/update-comment.dto.ts
  back/src/comments/entities/comment.entity.ts
  back/src/likeds/dto/create-liked.dto.ts
  back/src/likeds/dto/update-liked.dto.ts
  back/src/likeds/entities/liked.entity.ts
  back/src/likeds/liked.repository.ts
  back/src/likeds/likeds.controller.spec.ts
  back/src/likeds/likeds.controller.ts
  back/src/likeds/likeds.module.ts
  back/src/likeds/likeds.service.spec.ts
  back/src/likeds/likeds.service.ts
  back/src/post/entities/post.entity.ts
  back/src/users/entities/user.entity.ts
  back/yarn.lock
Labels: backend

#104 [W3][D4][뚱이] back, front 오류 해결
  back/src/app.controller.spec.ts
  back/src/app.controller.ts
  back/src/app.module.ts
  back/src/app.service.ts
  back/src/likeds/dto/create-liked.dto.ts
  back/src/likeds/dto/update-liked.dto.ts
  back/src/likeds/entities/liked.entity.ts
  back/src/likeds/liked.repository.ts
  back/src/likeds/likeds.controller.spec.ts
  back/src/likeds/likeds.controller.ts
  back/src/likeds/likeds.module.ts
  back/src/likeds/likeds.service.spec.ts
  back/src/likeds/likeds.service.ts
  front/src/reset.css
Labels: bug, frontend

#107 [잔업][징징이] path alias, global style 적용
  front/craco.config.js
  front/package.json
  front/src/App.tsx
  front/src/assets/fonts/NanumPenScript-Regular.ttf
  front/src/assets/fonts/OFL.txt
  front/src/components/DeleteModal/DeleteModal.tsx
  front/src/components/DetailModal/DetailModal.tsx
  front/src/components/DetailModal/PreviewBox.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedFAB.tsx
  front/src/components/Feed/FeedScrollBox.tsx
  front/src/components/Habitat/HabitatPreview.tsx
  front/src/components/HabitatModal/HabitatModal.tsx
  front/src/components/HabitatModal/HabitatsContainer.tsx
  front/src/components/Header/Header.tsx
  front/src/components/Header/Place.tsx
  front/src/components/Header/UserInfo.tsx
  front/src/components/HeartButton/HeartButton.tsx
  front/src/components/Write/Preview.tsx
  front/src/components/Write/WriteModal.tsx
  front/src/components/_common/Carousel/Arrow.tsx
  front/src/components/_common/Carousel/Carousel.tsx
  front/src/components/_common/Carousel/Dots.tsx
  front/src/components/_common/Carousel/Slide.tsx
  front/src/components/_common/Carousel/useMoveSlide.ts
  front/src/components/_common/DropBox/DropBox.tsx
  front/src/components/_common/Modal/Modal.tsx
  front/src/components/_common/SwipeBox/SwipeBox.tsx
  front/src/index.tsx
  front/src/lib/styles/GlobalStyle.ts
  front/src/pages/MainPage.tsx
  front/src/react-app-env.d.ts
  front/tsconfig.json
  front/tsconfig.paths.json
Labels: frontend

#111 [잔업][징징이] 피드 컨테이너 리팩토링
  front/src/App.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/components/Feed/FeedScrollBox.tsx
  front/src/components/Feed/ScrollBoxContainer.tsx
  front/src/components/Feed/ViewPort.tsx
  front/src/components/_common/Carousel/Arrow.tsx
  front/src/components/_common/Carousel/Carousel.tsx
  front/src/components/_common/Carousel/Slide.tsx
  front/src/global.css
  front/src/hooks/useClientRect.ts
  front/src/hooks/useFetch.ts
  front/src/hooks/useGetDiv.ts
  front/src/hooks/useIntersectionObserver.ts
  front/src/hooks/useScroll.ts
  front/src/lib/styles/GlobalStyle.ts
  front/src/lib/styles/fonts.css
  front/src/pages/MainPage.tsx
  front/src/reset.css
Labels: frontend

#112 [잔업][스폰지밥] 구조 수정 및 좋아요 API 추가
  back/src/comments/comment.repository.ts
  back/src/comments/entities/comment.entity.ts
  back/src/comments/spec/comments.controller.spec.ts
  back/src/comments/spec/comments.service.spec.ts
  back/src/hearts/dto/create-heart.dto.ts
  back/src/hearts/dto/update-heart.dto.ts
  back/src/hearts/heart.repository.ts
  back/src/hearts/hearts.controller.ts
  back/src/hearts/hearts.module.ts
  back/src/hearts/hearts.service.ts
  back/src/hearts/spec/hearts.controller.spec.ts
  back/src/hearts/spec/hearts.service.spec.ts
  back/src/main.ts
Labels: backend

#128 [W4][D1][다람이] 로그인 모달 레이아웃 구현
  front/src/components/HabitatModal/HabitatModal.tsx
  front/src/components/Header/Header.tsx
  front/src/components/Header/UserInfo.tsx
  front/src/components/LoginModal/LoginModal.tsx
  front/src/components/Write/WriteModal.tsx
  front/src/components/_common/DropBox/DropBox.tsx
  front/src/lib/styles/Palette.ts
  front/src/lib/styles/mixin.ts
  front/yarn.lock
Labels: frontend

#133 [W4][D2][징징이] 회원가입 페이지 구현 및 연동
  front/package.json
  front/src/components/Button/Button.tsx
  front/src/components/Header/UserInfo.tsx
  front/src/components/LoginModal/LoginModal.tsx
  front/src/components/Register/AccountInfo.tsx
  front/src/components/Register/MoreInfo.tsx
  front/src/components/Register/Register.tsx
  front/src/components/Register/Transition.css
  front/src/components/_common/Input/Input.tsx
  front/src/components/_common/Select/Select.tsx
  front/src/hooks/useForm.ts
  front/src/hooks/usePageSlide.ts
  front/src/index.tsx
  front/src/pages/RegisterPage.tsx
Labels: frontend

#131 [W4][D2][다람이] 탐험모드 화면 전환 구현
  front/src/assets/icons/home.svg
  front/src/assets/icons/zoom_in.svg
  front/src/components/Explore/Explore.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/components/Feed/FeedFAB.tsx
  front/src/components/Habitat/HabitatPreview.tsx
  front/src/pages/MainPage.tsx
Labels: frontend

#140 [W4][D3][뚱이] 회원 가입 API 구현
  back/.prettierrc
  back/package.json
  back/pipes/validation-sign-up.pipe.ts
  back/src/users/dto/create-user.dto.ts
  back/src/users/entities/user.entity.ts
  back/src/users/user.repository.ts
  back/src/users/users.controller.ts
  back/src/users/users.service.ts
  back/tsconfig.paths.json
  back/utils/s3.util.ts
  back/yarn.lock
Labels: backend

#142 [W4][D3][징징이] 회원가입 페이지 보완, 서식지 모달 일부 구현
  front/src/assets/icons/photo_camera.svg
  front/src/assets/images/default_avatar.png
  front/src/components/HabitatModal/HabitatModal.tsx
  front/src/components/HabitatModal/HabitatsContainer.tsx
  front/src/components/Header/Header.tsx
  front/src/components/Register/MoreInfo.tsx
  front/src/components/Register/Register.tsx
  front/src/hooks/useForm.ts
  front/src/hooks/useHistory.ts
  front/src/hooks/usePageSlide.ts
  front/src/hooks/useReadFileURL.ts
  front/src/pages/MainPage.tsx
Labels: frontend

#141 [W4][D3][다람이] 상세보기 모달 구현
  front/src/assets/icons/delete.svg
  front/src/assets/icons/edit.svg
  front/src/components/DetailModal/Comment.tsx
  front/src/components/DetailModal/CommentForm.tsx
  front/src/components/DetailModal/CommentList.tsx
  front/src/components/DetailModal/DetailModal.tsx
  front/src/components/DetailModal/HeartSection.tsx
  front/src/components/DetailModal/PreviewBox.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/components/_common/Carousel/Slide.tsx
  front/src/components/_common/DropBox/DropBox.tsx
  front/src/hooks/useSideNavi.ts
  front/src/lib/styles/Palette.ts
  front/src/lib/styles/mixin.ts
  front/src/pages/MainPage.tsx
  front/yarn.lock
Labels: frontend

#144 [W4][D3][스폰지밥] 이미지 리사이징 구현
  back/config/s3.config.ts
  back/package-lock.json
  back/package.json
  back/utils/s3.util.ts
  back/yarn.lock
Labels: backend

#149 [W4][D4][스폰지밥] 패키지 오류 해결 및 리팩토링 Hotfix
  back/common/dto/transformFileDto.ts
  back/common/pipes/parse-optional-int.pipe.ts
  back/common/pipes/validation-sign-up.pipe.ts
  back/config/s3.config.ts
  back/package-lock.json
  back/package.json
  back/src/post/post.controller.ts
  back/src/users/users.controller.ts
  back/utils/s3.util.ts
  back/yarn.lock
Labels: backend

#154 [W4][D4][스폰지밥&징징이&뚱이&다람이] 작업 동기화 2차
  back/src/auth/auth.service.ts
  back/src/comments/comment.repository.ts
  back/src/comments/comments.controller.ts
  back/src/comments/comments.service.ts
  back/src/comments/dto/cursor-pagination.dto.ts
  back/src/contents/entities/content.entity.ts
  back/src/users/entities/user.entity.ts
  back/src/users/user.repository.ts
  back/src/users/users.controller.ts
  back/src/users/users.service.ts
  front/src/components/Register/AccountInfo.tsx
  front/src/components/Register/MoreInfo.tsx
  front/src/components/Register/Register.tsx
  front/src/contexts/UserContext.tsx
  front/src/hooks/usePageSlide.ts
  front/src/hooks/useSideNavi.ts
Labels: frontend, backend, refactoring

#165 [잔업][징징이] 이번 주 테스크 마무리
  front/src/components/DetailModal/CommentForm.tsx
  front/src/components/DetailModal/CommentList.tsx
  front/src/components/DetailModal/DetailModal.tsx
  front/src/components/DetailModal/HeartSection.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/components/HabitatModal/HabitatModal.tsx
  front/src/components/HabitatModal/HabitatsContainer.tsx
  front/src/components/HeartButton/useLike.ts
  front/src/components/_common/Carousel/Carousel.tsx
  front/src/hooks/useFetch.ts
  front/src/hooks/useFetchTotalFeeds.ts
  front/src/hooks/useForm.ts
  front/src/hooks/useScroll.ts
  front/src/hooks/useSideNavi.ts
  front/src/lib/constants/timeUnit.ts
  front/src/lib/utils/queryString.ts
  front/src/lib/utils/time.ts
  front/src/pages/MainPage.tsx
  front/src/types/Post.ts
Labels: bug, frontend

#162 [잔업][다람이] 글쓰기 모달 api 연결 & 드롭박스 버그 수정
  front/src/components/Write/WriteModal.tsx
  front/src/components/_common/DropBox/DropBox.tsx
  front/src/components/_common/Modal/Modal.tsx
Labels: bug, frontend

#167 [잔업][뚱이] Swagger 적용 및 버그 수정
  back/common/dto/file-upload.dto.ts
  back/common/dto/files-upload.dto.ts
  back/config/database.config.ts
  back/src/auth/auth.service.ts
  back/src/main.ts
  back/src/post/dto/create-post.dto.ts
  back/src/post/dto/patchPostRequestDto.ts
  back/src/post/post.controller.ts
  back/src/post/post.module.ts
  back/src/post/post.service.ts
  back/src/users/users.controller.ts
Labels: bug, backend, setting, refactoring

#173 [잔업][스폰지밥] Swagger 적용 및 species , follow api 추가
  back/common/dto/cursor-pagination.dto.ts
  back/src/app.module.ts
  back/src/comments/comment.repository.ts
  back/src/comments/comments.controller.ts
  back/src/comments/comments.service.ts
  back/src/comments/dto/comments-cursor-pagination.dto.ts
  back/src/contents/contents.controller.ts
  back/src/contents/contents.module.ts
  back/src/contents/contents.service.ts
  back/src/contents/dto/update-content.dto.ts
  back/src/contents/spec/contents.controller.spec.ts
  back/src/contents/spec/contents.service.spec.ts
  back/src/follow/dto/create-follow.dto.ts
  back/src/follow/dto/update-follow.dto.ts
  back/src/follow/entities/follow.entity.ts
  back/src/follow/follow.controller.ts
  back/src/follow/follow.module.ts
  back/src/follow/follow.repository.ts
  back/src/follow/follow.service.ts
  back/src/main.ts
  back/src/species/dto/create-species.dto.ts
  back/src/species/species.controller.ts
  back/src/species/species.module.ts
  back/src/species/species.repository.ts
  back/src/species/species.service.ts
  back/utils/s3.util.ts
Labels: backend

#194 [W5][D1][스폰지밥&뚱이] 변경사항 병합
  back/src/follow/follow.controller.ts
  back/src/main.ts
  back/src/post/post.controller.ts
  back/src/users/users.controller.ts
Labels: backend

#203 [W5][D1][다람이] 리버스 프록싱 적용&탐험하기 간소화 구현
  front/conf/conf.d/default.conf
  front/package.json
  front/src/App.tsx
  front/src/components/Explore/Cell.tsx
  front/src/components/Explore/Explore.tsx
  front/src/components/Habitat/HabitatPreview.tsx
  front/src/components/HabitatModal/HabitatModal.tsx
  front/src/components/HeartButton/useLike.ts
  front/src/components/LoginModal/LoginModal.tsx
  front/src/components/Write/WriteModal.tsx
  front/src/contexts/UserContext.tsx
  front/src/hooks/useFetchTotalFeeds.ts
  front/src/hooks/useHabitatInfo.ts
  front/src/hooks/usePageSlide.ts
  front/src/hooks/useSideNavi.ts
  front/src/pages/TestPage.tsx
  front/src/types/Habitat.ts
  front/src/types/Post.ts
Labels: bug, frontend, setting

#201 [W5][D1][뚱이] User, Post API 수정 및 추가
  back/src/post/post.controller.ts
  back/src/post/post.service.ts
  back/src/users/dto/create-user.dto.ts
  back/src/users/dto/register-user.dto.ts
  back/src/users/entities/user.entity.ts
  back/src/users/user.repository.ts
  back/src/users/users.controller.ts
  back/src/users/users.service.ts
  back/utils/value-converter.util.ts
Labels: backend, refactoring

#204 [W5][D1][스폰지밥] 로깅 구현 , 이미지 리사이징 수정
  back/config/database.config.ts
  back/config/logger.config.ts
  back/config/s3.config.ts
  back/logger/logger.controller.ts
  back/logger/logger.service.ts
  back/package.json
  back/src/app.module.ts
  back/src/habitat/habitat.controller.ts
  back/src/habitat/habitat.service.ts
  back/src/main.ts
  back/src/post/post.controller.ts
  back/src/species/dto/create-species.dto.ts
  back/src/species/species.controller.ts
  back/src/species/species.service.ts
  back/yarn.lock
Labels: bug, backend, setting

#210 [W5][D2][다람이] 유저 페이지 구현, 글삭제, 글수정 모달 api 연결
  front/src/App.tsx
  front/src/components/DeleteModal/DeleteModal.tsx
  front/src/components/DetailModal/DetailContainer.tsx
  front/src/components/DetailModal/DetailModal.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/components/Header/UserInfo.tsx
  front/src/components/User/FeedCell.tsx
  front/src/components/User/UserAbout.tsx
  front/src/components/User/UserFeed.tsx
  front/src/components/Write/WriteModal.tsx
  front/src/components/_common/Avatar/Avatar.tsx
  front/src/pages/UserPage.tsx
  front/src/types/User.ts
Labels: frontend

#213 [W5][D2][뚱이] refresh token 구현
  back/config/auth.config.ts
  back/config/database.config.ts
  back/package.json
  back/src/auth/auth.module.ts
  back/src/auth/auth.service.ts
  back/src/auth/jwt-auth.guard.ts
  back/src/main.ts
  back/src/post-contents/entities/post-content.entity.ts
  back/src/post/dto/user-post.dto.ts
  back/src/post/post.controller.ts
  back/src/post/post.repository.ts
  back/src/post/post.service.ts
  back/src/refresh-tokens/entities/refresh-token.entity.ts
  back/src/refresh-tokens/refresh-token.repository.ts
  back/src/users/users.controller.ts
  back/src/users/users.module.ts
  back/src/users/users.service.ts
  back/yarn.lock
Labels: bug, backend

#211 [W5][D2][징징이] 버그 수정, 댓글 API 연동, 회원가입 추가 UI 구현
  back/config/auth.config.ts
  back/config/database.config.ts
  back/config/logger.config.ts
  back/config/s3.config.ts
  back/logger/logger.controller.ts
  back/logger/logger.service.ts
  back/package.json
  back/src/app.module.ts
  back/src/auth/auth.module.ts
  back/src/auth/auth.service.ts
  back/src/auth/jwt-auth.guard.ts
  back/src/habitat/habitat.controller.ts
  back/src/habitat/habitat.service.ts
  back/src/main.ts
  back/src/post-contents/entities/post-content.entity.ts
  back/src/post/dto/user-post.dto.ts
  back/src/post/post.controller.ts
  back/src/post/post.repository.ts
  back/src/post/post.service.ts
  back/src/refresh-tokens/entities/refresh-token.entity.ts
  back/src/refresh-tokens/refresh-token.repository.ts
  back/src/species/dto/create-species.dto.ts
  back/src/species/species.controller.ts
  back/src/species/species.service.ts
  back/src/users/users.controller.ts
  back/src/users/users.module.ts
  back/src/users/users.service.ts
  back/yarn.lock
  front/src/components/DetailModal/Comment.tsx
  front/src/components/DetailModal/CommentList.tsx
  front/src/components/DetailModal/DetailModal.tsx
  front/src/components/DetailModal/HeartSection.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/components/HabitatModal/HabitatModal.tsx
  front/src/components/HabitatModal/HabitatsContainer.tsx
  front/src/components/HeartButton/useLike.ts
  front/src/components/Register/AccountInfo.tsx
  front/src/components/Register/HabitatsMakeModal.tsx
  front/src/components/Register/MoreInfo.tsx
  front/src/components/Register/Register.tsx
  front/src/components/Register/SpeciesMakeModal.tsx
  front/src/components/Register/useForm.ts
  front/src/components/User/FeedCell.tsx
  front/src/components/_common/Avatar/Avatar.tsx
  front/src/components/_common/Input/Input.tsx
  front/src/components/_common/Select/Select.tsx
  front/src/contexts/RegisterContext.tsx
  front/src/hooks/useElementRef.ts
  front/src/hooks/useForm.ts
  front/src/hooks/useGetFetch.ts
  front/src/hooks/usePageSlide.ts
  front/src/hooks/useSideNavi.ts
  front/src/pages/MainPage.tsx
  front/src/pages/RegisterPage.tsx
  front/src/types/Comment.ts
  front/src/types/Habitat.ts
  front/src/types/Post.ts
  front/src/types/Species.ts
  front/yarn.lock
Labels: bug, frontend

#217 [W5][D3][뚱이] 게시물, 유저 API 수정
  back/src/auth/jwt-auth.guard.ts
  back/src/post/post.service.ts
  back/src/users/users.service.ts
Labels: backend

#219 [W5][D3][스폰지밥] bulk insert, 리사이징 로직 수정
  back/config/s3.config.ts
  back/db/docker-compose.yml
  back/db/dummy_insert.py
  back/src/users/users.controller.ts
Labels: backend, devops

#221 [W5][D3][뚱이&다람이] 글수정 구현 완료/각종 버그 해결
  back/config/auth.config.ts
  back/src/auth/optional-jwt.strategy.ts
  back/src/post/post.service.ts
  back/src/users/users.controller.ts
  back/src/users/users.service.ts
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/components/Header/UserInfo.tsx
  front/src/components/LoginModal/LoginModal.tsx
  front/src/components/Write/Preview.tsx
  front/src/components/Write/WriteModal.tsx
  front/src/contexts/UserContext.tsx
  front/src/hooks/useSideNavi.ts
  front/src/pages/MainPage.tsx
  front/src/types/Post.ts
Labels: bug, frontend, backend

#226 [W5][D3][뚱이&다람이] 협업 구현
  back/src/auth/auth.module.ts
  back/src/auth/optional-jwt-auth.guard.ts
  back/src/post/post.controller.ts
  back/src/post/post.service.ts
  back/src/users/users.controller.ts
  front/src/assets/icons/loading.svg
  front/src/components/DetailModal/PreviewBox.tsx
  front/src/components/Explore/Cell.tsx
  front/src/components/Explore/Explore.tsx
  front/src/components/Habitat/HabitatPreview.tsx
  front/src/components/User/FeedCell.tsx
  front/src/components/User/UserAbout.tsx
  front/src/components/_common/Avatar/Avatar.tsx
  front/src/components/_common/Carousel/Slide.tsx
  front/src/contexts/UserContext.tsx
  front/src/hooks/useHabitatInfo.ts
  front/src/hooks/useValidateUser.ts
  front/src/pages/MainPage.tsx
  front/src/pages/UserPage.tsx
  front/src/types/User.ts
Labels: bug, backend

#230 [W5][D3][뚱이] refresh token 수정
  back/config/database.config.ts
  back/src/auth/auth.module.ts
  back/src/auth/auth.service.ts
  back/src/refresh-tokens/entities/refresh-token.entity.ts
  back/src/refresh-tokens/refresh-token.repository.ts
  back/src/users/entities/user.entity.ts
  back/src/users/users.controller.ts
  back/src/users/users.module.ts
  back/src/users/users.service.ts
Labels: backend, refactoring

#231 [W5][D3][스폰지밥] API 버그 수정
  back/config/s3.config.ts
  back/src/habitat/habitat.service.ts
  back/src/post/post.repository.ts
  back/src/post/post.service.ts
Labels: bug, backend

#239 [W5][D4][다람이] useSideNavi 리팩토링 및 각종 버그 해결
  front/src/components/Explore/Cell.tsx
  front/src/components/Habitat/HabitatPreview.tsx
  front/src/hooks/useSideNavi.ts
  front/src/pages/MainPage.tsx
  front/yarn.lock
Labels: bug, frontend

#241 [W5][D4][다람이] 피드 번역 UI 구현 / 서식지 버그 수정
  front/src/components/DetailModal/PreviewBox.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/hooks/useHabitatInfo.ts
  front/src/hooks/useSideNavi.ts
Labels: bug, frontend

#246 [W5][D4][다람이] 라우팅 관련 버그 해결 / 상태 지시 컴포넌트 구현
  front/src/assets/icons/warning.svg
  front/src/components/Explore/Explore.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/components/Feed/useDetailFeed.ts
  front/src/components/Habitat/HabitatPreview.tsx
  front/src/components/Header/Header.tsx
  front/src/components/Header/Place.tsx
  front/src/components/_common/Indicator/Loading.tsx
  front/src/components/_common/Indicator/Warning.tsx
  front/src/hooks/useFetchTotalFeeds.ts
  front/src/hooks/useHabitatInfo.ts
  front/src/hooks/useSideNavi.ts
  front/src/pages/UserPage.tsx
Labels: bug, frontend

#247 [W5][D4][뚱이] 번역 + 회원가입 +
  back/src/habitat/entities/habitat.entity.ts
  back/src/post/post.module.ts
  back/src/post/post.service.ts
  back/src/users/dto/create-user.dto.ts
  back/src/users/dto/register-user.dto.ts
  back/src/users/user.repository.ts
  back/src/users/users.controller.ts
  back/src/users/users.service.ts
  back/utils/condition-check.util.ts
Labels: backend, refactoring

#248 [W5][D4][다람이] 게시글 조회 쿼리 성능 개선
  back/src/post/post.service.ts
Labels: backend

#249 [W5][D4][스폰지밥] 서식지 API 버그 수정
  back/src/habitat/habitat.service.ts
Labels: backend

#251 [W5][D4][징징이] 회원가입 마무리
  front/src/components/Register/MoreInfo.tsx
  front/src/components/Register/ProfileImage.tsx
  front/src/contexts/RegisterContext.tsx
Labels: frontend

#252 [W5][D4][뚱이] backend dockerfile 수정
  back/Dockerfile
  back/package-lock.json
  back/package.json
Labels: backend, setting

#262 [잔업][다람이] 각종 버그 해결 / 중복 제거 / 상세보기 댓글 로직 연결
  front/src/components/DeleteModal/DeleteModal.tsx
  front/src/components/DetailModal/Comment.tsx
  front/src/components/DetailModal/CommentForm.tsx
  front/src/components/DetailModal/CommentList.tsx
  front/src/components/DetailModal/DetailModal.tsx
  front/src/components/DetailModal/useCommentList.ts
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/useDetailFeed.ts
  front/src/components/Habitat/HabitatPreview.tsx
  front/src/components/Write/WriteModal.tsx
  front/src/hooks/useValidateUser.ts
  front/src/lib/utils/fetch.ts
  front/src/lib/utils/time.ts
  front/src/types/Habitat.ts
Labels: bug, frontend

#274 [잔업][뚱이] api path 수정, 부하테스트 조금
  back/package.json
  back/src/users/entities/user.entity.ts
  back/src/users/user.repository.ts
  back/src/users/users.controller.ts
  back/src/users/users.service.ts
  front/public/index.html
Labels: bug, backend, devops, refactoring

#273 [잔업][스폰지밥] 이미지 버그수정 및 인증로직 수정
  back/config/database.config.ts
  back/config/s3.config.ts
  back/src/comments/comments.controller.ts
  back/src/habitat/habitat.controller.ts
  back/src/hearts/hearts.controller.ts
  back/src/main.ts
  back/src/post/post.controller.ts
  back/src/species/species.controller.ts
  back/src/users/users.controller.ts
  back/utils/s3.util.ts
Labels: bug, backend

#277 [W6][D1][뚱이] 코드 리팩토링 및 오류 수정
  back/common/constants/nums.ts
  back/src/post/dto/create-post.dto.ts
  back/src/post/dto/patchPostRequestDto.ts
  back/src/post/post.controller.ts
  back/src/post/post.repository.ts
  back/src/post/post.service.ts
  back/src/users/dto/create-user.dto.ts
  back/src/users/users.controller.ts
  back/src/users/users.service.ts
  back/utils/condition-check.util.ts
Labels: bug, backend, refactoring

#278 [W6][D1][다람이] 댓글 관련 기능 구현 완료 / 버그 해결 / fetch 리팩토링
  front/src/components/DetailModal/Comment.tsx
  front/src/components/DetailModal/CommentForm.tsx
  front/src/components/DetailModal/CommentList.tsx
  front/src/components/DetailModal/DetailModal.tsx
  front/src/components/DetailModal/PreviewBox.tsx
  front/src/components/DetailModal/useCommentList.ts
  front/src/components/Feed/FeedContainer.tsx
  front/src/lib/utils/fetch.ts
Labels: bug, frontend, refactoring

#279 [W6][D1][징징이] file Input 로딩 창, 좋아요, useScroll 리팩토링
  front/src/App.tsx
  front/src/components/DetailModal/DetailContainer.tsx
  front/src/components/DetailModal/DetailModal.tsx
  front/src/components/DetailModal/HeartSection.tsx
  front/src/components/Explore/Explore.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/components/Feed/useDetailFeed.ts
  front/src/components/HeartButton/useLike.ts
  front/src/components/Register/AccountInfo.tsx
  front/src/components/Register/MoreInfo.tsx
  front/src/components/Register/ProfileImage.tsx
  front/src/components/Register/useFetchVerification.ts
  front/src/components/User/UserAbout.tsx
  front/src/contexts/RegisterContext.tsx
  front/src/contexts/ScrollContext.tsx
  front/src/hooks/useFetchTotalFeeds.ts
  front/src/hooks/useScroll.ts
  front/src/hooks/useSideNavi.ts
  front/src/pages/MainPage.tsx
  front/src/types/Modal.ts
Labels: frontend

#280 [W6][D1][스폰지밥] API 애러 핸들링 추가
  back/common/dto/cursor-pagination.dto.ts
  back/common/dto/pagination-query.dto.ts
  back/common/error/AllExceptionsFilter.ts
  back/config/swagger.config.ts
  back/src/comments/comments.controller.ts
  back/src/comments/comments.service.ts
  back/src/comments/dto/comments-cursor-pagination.dto.ts
  back/src/comments/dto/create-comment.dto.ts
  back/src/hearts/hearts.service.ts
  back/src/main.ts
  back/src/species/dto/create-species.dto.ts
  back/src/species/species.controller.ts
Labels: backend

#284 [W6][D2][스폰지밥] hotfix
  back/common/dto/cursor-pagination.dto.ts
  back/common/dto/pagination-query.dto.ts
  back/src/comments/dto/comments-cursor-pagination.dto.ts
  back/src/comments/dto/create-comment.dto.ts
  front/src/components/HeartButton/useLike.ts
Labels: frontend, backend

#288 [W6][D2][뚱이] Post, User Validator 적용
  back/common/dto/cursor-pagination.dto.ts
  back/common/dto/pagination-query.dto.ts
  back/common/pipes/parse-optional-string.pipe.ts
  back/config/auth.config.ts
  back/src/post/dto/create-post.dto.ts
  back/src/post/dto/getPostListResponse.dto.ts
  back/src/post/dto/getPostResponse.dto.ts
  back/src/post/post.controller.ts
  back/src/post/post.service.ts
  back/src/users/dto/create-user.dto.ts
  back/src/users/dto/verify-user.dto.ts
  back/src/users/users.controller.ts
Labels: backend, refactoring

#287 [W6][D2][다람이] 각종 버그 수정 / UIUX 개선
  front/src/App.tsx
  front/src/assets/icons/explore.svg
  front/src/components/DetailModal/CommentForm.tsx
  front/src/components/Explore/Explore.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedFAB.tsx
  front/src/components/Header/Header.tsx
  front/src/components/Header/Place.tsx
  front/src/components/Header/UserInfo.tsx
  front/src/components/LoginModal/LoginModal.tsx
  front/src/components/Write/WriteModal.tsx
  front/src/contexts/UserContext.tsx
  front/src/pages/ErrorPage.tsx
  front/src/pages/ExplorePage.tsx
Labels: bug, frontend

#289 [W6][D2][징징이] 검색기능 및 버그 수정
  front/src/components/DetailModal/DetailContainer.tsx
  front/src/components/DetailModal/DetailModal.tsx
  front/src/components/DetailModal/HeartSection.tsx
  front/src/components/Explore/Explore.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/components/HabitatModal/HabitatModal.tsx
  front/src/components/HabitatModal/HabitatsContainer.tsx
  front/src/components/HeartButton/useLike.ts
  front/src/contexts/ScrollContext.tsx
  front/src/hooks/useDebounce.ts
  front/src/hooks/useScroll.ts
  front/src/pages/MainPage.tsx
Labels: bug, frontend

#292 fix: 회원 중복 검사 수정
  back/src/users/users.controller.ts
Labels: bug, backend

#291 [W6][D2][다람이] 버그 수정
  front/src/components/User/UserFeed.tsx
  front/src/components/Write/Preview.tsx
  front/src/components/Write/WriteModal.tsx
Labels: bug, frontend
