Repository boostcampwm-2021/web20-PingPingsFriends, pull requests merged in 2021-12, with the labels that each got.

#294 [W6][D2][뚱이] logout 구현 미완료
  back/src/users/users.controller.ts
  back/src/users/users.service.ts
Labels: backend

#293 [W6][D2][다람이] fetch API 적용중
  back/common/error/AllExceptionsFilter.ts
  back/src/auth/auth.module.ts
  back/src/auth/jwt-refresh-auth.guard.ts
  back/src/auth/jwt-refresh.strategy.ts
  back/src/auth/local.strategy.ts
  back/src/users/users.controller.ts
  front/src/components/DeleteModal/DeleteModal.tsx
  front/src/components/DetailModal/CommentForm.tsx
  front/src/components/Feed/useDetailFeed.ts
  front/src/components/HeartButton/useLike.ts
  front/src/components/LoginModal/LoginModal.tsx
  front/src/components/User/FeedCell.tsx
  front/src/components/User/UserAbout.tsx
  front/src/contexts/UserContext.tsx
  front/src/hooks/useValidateUser.ts
  front/src/lib/utils/fetch.ts
Labels: frontend

#295 [W6][D2][징징이] 유저 페이지 헤더 모달 수정
  front/src/App.tsx
  front/src/components/_common/Modal/Modal.tsx
  front/src/components/_common/Modal/useModal.tsx
  front/src/hooks/useScrollObserver.ts
  front/src/pages/MainArticle.tsx
  front/src/pages/MainPage.tsx
  front/src/pages/UserArticle.tsx
Labels: frontend

#299 [W6][D3][다람이] fetchAPI 적용 완료
  front/src/components/DetailModal/CommentForm.tsx
  front/src/hooks/useFetchTotalFeeds.ts
  front/src/hooks/useValidateUser.ts
  front/src/lib/utils/fetch.ts
Labels: frontend, refactoring

#298 [W6][D3][징징이] 로그아웃, fetch 리팩토링
  back/src/users/users.service.ts
  front/src/components/Header/UserInfo.tsx
  front/src/components/_common/DropBox/DropBox.tsx
  front/src/contexts/ScrollContext.tsx
Labels: frontend, refactoring

#302 [W6][D3][뚱이] 게시물 삭제, 조회 오류 수정 최종
  back/config/auth.config.ts
  back/config/database.config.ts
  back/src/auth/auth.module.ts
  back/src/auth/auth.service.ts
  back/src/auth/optional-jwt-auth.guard.ts
  back/src/auth/optional-jwt.strategy.ts
  back/src/hearts/entities/heart.entity.ts
  back/src/post/post.controller.ts
  back/src/post/post.module.ts
Labels: bug, backend

#301 [W6][D3][징징이] 더미 파일 제거, 이미지 URL 변경, 생성 시간 표기 수정
  front/public/cat.jpg
  front/public/dog.jpeg
  front/public/dummy_feed.json
  front/public/habitat/0.json
  front/public/habitat/1.json
  front/public/habitat/2.json
  front/public/제리.mp4
  front/public/제리2.mp4
  front/src/components/User/FeedCell.tsx
  front/src/components/_common/Input/Input.tsx
  front/src/lib/utils/time.ts
Labels: frontend

#303 [W6][D3][뚱이] config 파일 수정
  back/config/database.config.ts
Labels: backend, refactoring

#305 [W6][D3][징징이] 각종 hotfix
  front/src/App.tsx
  front/src/components/DetailModal/HeartSection.tsx
  front/src/components/Feed/useDetailFeed.ts
  front/src/components/Register/ProfileImage.tsx
  front/src/components/User/UserAbout.tsx
  front/src/hooks/useFileInputAlert.ts
Labels: bug, frontend

#307 [W6][D3][스폰지밥] 회원가입 좋아요 fix
  back/src/hearts/hearts.service.ts
  front/src/components/Register/MoreInfo.tsx
Labels: bug, frontend, backend

#306 [W6][D3][뚱이] 각종 hotfix
  back/common/dto/pagination-query.dto.ts
  back/src/post/post.service.ts
  back/src/users/dto/create-user.dto.ts
Labels: bug, backend

#304 [W6][D3][다람이] 각종 hotfix
  front/src/components/DetailModal/Comment.tsx
  front/src/components/DetailModal/CommentForm.tsx
  front/src/components/_common/Avatar/Avatar.tsx
  front/src/pages/MainArticle.tsx
Labels: bug, frontend

#308 [W6][D3][징징이] 좋아요 피드->모달 연동
  front/src/components/DetailModal/DetailModal.tsx
  front/src/components/DetailModal/HeartSection.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/components/HeartButton/useLike.ts
Labels: bug, frontend

#310 [찐찐찐막][뚱이] 마무리 작업
  back/config/auth.config.ts
  back/src/users/users.controller.ts
Labels: backend, setting

#312 [찐찐찐찐막][징징이] 글 수정 모달 / 유저페이지 뒤로가기 버그 수정
  front/src/components/DetailModal/DetailContainer.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/components/_common/Avatar/Avatar.tsx
  front/src/contexts/ScrollContext.tsx
  front/src/hooks/useSideNavi.ts
  front/src/pages/MainArticle.tsx
  front/src/pages/MainPage.tsx
Labels: bug, frontend

#313 [찐찐찐찐막][다람이] 글 작성 시 비디오, gif 첨부 방지
  front/src/components/Write/WriteModal.tsx
  front/src/pages/UserArticle.tsx
Labels: bug, frontend

#314 [찐6막][징징이] 회원가입 로딩 모달 수정
  front/src/components/Register/ProfileImage.tsx
  front/src/components/User/UserAbout.tsx
Labels: bug, frontend

#315 [찐7막][다람이] useSideNavi 불필요한 fetch 요청 제거
  front/src/hooks/useSideNavi.ts
  front/src/pages/MainArticle.tsx
Labels: bug, frontend

#316 version 1.0.1 release
  front/src/components/DetailModal/DetailContainer.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/components/Register/ProfileImage.tsx
  front/src/components/User/UserAbout.tsx
  front/src/components/Write/WriteModal.tsx
  front/src/components/_common/Avatar/Avatar.tsx
  front/src/contexts/ScrollContext.tsx
  front/src/hooks/useSideNavi.ts
  front/src/pages/MainArticle.tsx
  front/src/pages/MainPage.tsx
  front/src/pages/UserArticle.tsx
Labels: frontend, backend, release

#317 진짜 마지막
  front/src/assets/fonts/NanumPenScript-Regular-subset.ttf
  front/src/assets/fonts/NanumSquareRoundOTFEB.otf
  front/src/assets/fonts/OFL.txt
  front/src/components/DetailModal/Comment.tsx
  front/src/components/DetailModal/CommentForm.tsx
  front/src/components/DetailModal/DetailModal.tsx
  front/src/components/DetailModal/HeartSection.tsx
  front/src/components/Explore/Cell.tsx
  front/src/components/Feed/Feed.tsx
  front/src/components/Feed/FeedContainer.tsx
  front/src/components/Feed/FeedFAB.tsx
  front/src/components/Feed/SkeletonFeeds.tsx
  front/src/components/Habitat/HabitatPreview.tsx
  front/src/components/Header/Header.tsx
  front/src/components/Header/Place.tsx
  front/src/components/Header/UserInfo.tsx
  front/src/components/LoginModal/LoginModal.tsx
  front/src/components/User/UserAbout.tsx
  front/src/components/Write/WriteModal.tsx
  front/src/components/_common/Avatar/Avatar.tsx
  front/src/components/_common/Carousel/Slide.tsx
  front/src/components/_common/Input/Input.tsx
  front/src/hooks/useScroll.ts
  front/src/lib/styles/GlobalStyle.ts
  front/src/lib/styles/fonts.css
Labels: bug
